version: '3.5'
services:

  postgres:
    container_name: postgres
    image: postgres:10.12-alpine
    extra_hosts:
      - "host.docker.internal:${DOCKER_HOST_IP}"
    volumes:
      - $HOME/workspace/myapp/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234

  api-myapp:
    container_name: api-myapp
    image: raulickis/api-myapp:latest
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:${DOCKER_HOST_IP}"
    ports:
      - '9990:9990'
